FROM quay.io/fedora/fedora:42

ARG USER_HOME_DIR="/home/user"
ARG WORK_DIR="/projects"
ARG NODE_VERSION="v20.19.0"
ENV HOME=${USER_HOME_DIR}
ENV BUILDAH_ISOLATION=chroot
ENV PATH=${PATH}:/usr/local/node/bin

COPY --chown=0:0 entrypoint.sh /
COPY oneAPI.repo /etc/yum.repos.d/

RUN dnf install -y awk g++ cmake git libcurl-devel intel-oneapi-base-toolkit intel-oneapi-mkl-sycl-devel intel-oneapi-dnnl-devel intel-oneapi-compiler-dpcpp-cpp intel-level-zero oneapi-level-zero oneapi-level-zero-devel intel-compute-runtime procps-ng python3.12 python3.12-devel lspci clinfo openssl libbrotli git tar gzip zip xz unzip which shadow-utils bash zsh vi wget jq podman buildah skopeo podman-docker ca-certificates fuse-overlayfs util-linux vim-minimal vim-enhanced awk libpng-devel libjpeg-devel libfabric-devel intel-deep-learning-essentials ; \
  dnf update -y ; \
  dnf clean all ; \
  mkdir -p /usr/local/bin ; \
  mkdir -p ${WORK_DIR} ; \
  python3.12 -m ensurepip ; \
  # Install NodeJS
  TEMP_DIR="$(mktemp -d)" ; \
  curl -fsSL -o ${TEMP_DIR}/node.tz https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz ; \
  tar -x --no-auto-compress -f ${TEMP_DIR}/node.tz -C ${TEMP_DIR} ; \
  mv ${TEMP_DIR}/node-${NODE_VERSION}-linux-x64 /usr/local/node ; \
  rm -rf "${TEMP_DIR}" ; \
  npm install -g fnm; \
  chgrp -R 0 /home ; \
  chmod -R g=u /home ${WORK_DIR} ; \
  chmod +x /entrypoint.sh ; \
  chown 0:0 /etc/passwd ; \
  chown 0:0 /etc/group ; \
  chmod g=u /etc/passwd /etc/group ; \
  # Setup for rootless podman
  setcap cap_setuid+ep /usr/bin/newuidmap ; \
  setcap cap_setgid+ep /usr/bin/newgidmap ; \
  touch /etc/subgid /etc/subuid ; \
  chown 0:0 /etc/subgid ; \
  chown 0:0 /etc/subuid ; \
  chmod -R g=u /etc/subuid /etc/subgid ; \
  # Create Sym Links for OpenShift CLI (Assumed to be retrieved by an init-container)
  ln -s /projects/bin/oc /usr/local/bin/oc ; \
  ln -s /projects/bin/kubectl /usr/local/bin/kubectl

USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/usr/libexec/podman/catatonit","--","/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
